-   id: pipenv-lock
    name: pipenv-lock
    description: Generate requirements.txt and requirements-dev.txt for Pipenv environment.
    entry: pipenv-lock-pre-commit-hook
    language: python
    files: ^Pipfile(\.lock)?$
